version: "2.1"

services:

  loragtwpktfwd:
    restart: always
    image: pastagringo/lorapacketforwarder_sx1302_eu
    privileged: true

  helium-miner:
    restart: always
    image: quay.io/team-helium/miner:latest-arm64
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-data:/var/data'
      - 'miner-log:/var/log/miner'
    environment:
      - 'REGION_OVERRIDE=EU868'

volumes:
  miner-data:
  miner-log:
